-- Mi Nutrición - esquema inicial para Supabase/PostgreSQL
-- Ejecutar una sola vez desde Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.patients (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    age integer check (age is null or (age >= 1 and age <= 120)),
    sex text,
    weight numeric(7,2) check (weight is null or weight > 0),
    height numeric(7,2) check (height is null or height > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.goals (
    patient_id uuid primary key references public.patients(id) on delete cascade,
    calories numeric(10,2) not null default 0 check (calories >= 0),
    protein numeric(10,2) not null default 0 check (protein >= 0),
    carbs numeric(10,2) not null default 0 check (carbs >= 0),
    fat numeric(10,2) not null default 0 check (fat >= 0),
    fiber numeric(10,2) not null default 0 check (fiber >= 0),
    water numeric(10,2) not null default 0 check (water >= 0),
    updated_at timestamptz not null default now()
);

create table if not exists public.food_log (
    id bigint generated by default as identity primary key,
    patient_id uuid not null references public.patients(id) on delete cascade,
    log_date date not null,
    meal text not null check (meal in ('Desayuno', 'Comida', 'Cena', 'Snack')),
    food text not null,
    quantity numeric(10,2) not null default 0 check (quantity >= 0),
    unit text not null,
    calories numeric(10,2) not null default 0 check (calories >= 0),
    protein numeric(10,2) not null default 0 check (protein >= 0),
    carbs numeric(10,2) not null default 0 check (carbs >= 0),
    fat numeric(10,2) not null default 0 check (fat >= 0),
    fiber numeric(10,2) not null default 0 check (fiber >= 0),
    water numeric(10,2) not null default 0 check (water >= 0),
    created_at timestamptz not null default now()
);

create index if not exists idx_food_log_patient_date
    on public.food_log(patient_id, log_date);

-- La app usa service_role desde el servidor de Streamlit.
-- Habilitamos RLS y NO creamos políticas públicas; de esta manera,
-- una publishable/anon key no puede leer ni escribir estas tablas.
alter table public.patients enable row level security;
alter table public.goals enable row level security;
alter table public.food_log enable row level security;

-- Acceso explícito para el rol de backend. Las Secret keys nuevas y la
-- service_role legacy operan con este rol y bypassan RLS.
grant usage on schema public to service_role;
grant all on table public.patients to service_role;
grant all on table public.goals to service_role;
grant all on table public.food_log to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Registro inicial del MVP. La app también puede recrearlo si se borra.
insert into public.patients (id, name, age, sex, weight, height)
values (
    '11111111-1111-1111-1111-111111111111',
    'Paciente demo',
    30,
    'Femenino',
    65,
    165
)
on conflict (id) do nothing;

insert into public.goals (
    patient_id, calories, protein, carbs, fat, fiber, water
)
values (
    '11111111-1111-1111-1111-111111111111',
    2000, 120, 220, 65, 30, 2500
)
on conflict (patient_id) do nothing;
