-- Mi Nutrición V0.5 - medidas caseras, cálculo de metas y composición corporal.
-- Requiere supabase_schema.sql y supabase_v04_catalog_migration.sql.
-- Ejecutar una sola vez desde Supabase > SQL Editor con el rol postgres.

alter table public.patients
    add column if not exists activity_level text not null default 'Sedentaria';

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'patients_activity_level_check'
          and conrelid = 'public.patients'::regclass
    ) then
        alter table public.patients
            add constraint patients_activity_level_check
            check (activity_level in ('Sedentaria', 'Ligera', 'Moderada', 'Alta', 'Muy alta'));
    end if;
end;
$$;

alter table public.goals
    add column if not exists calculation_method text,
    add column if not exists resting_calories numeric(10,2),
    add column if not exists activity_factor numeric(6,3),
    add column if not exists calorie_adjustment_pct numeric(6,2),
    add column if not exists protein_pct numeric(6,2),
    add column if not exists carbs_pct numeric(6,2),
    add column if not exists fat_pct numeric(6,2),
    add column if not exists water_ml_per_kg numeric(6,2);

create table if not exists public.body_measurements (
    id bigint generated by default as identity primary key,
    patient_id uuid not null references public.patients(id) on delete cascade,
    measured_on date not null default current_date,
    device text,
    bmi numeric(6,2) check (bmi is null or (bmi > 0 and bmi <= 100)),
    body_fat_pct numeric(6,2)
        check (body_fat_pct is null or (body_fat_pct > 0 and body_fat_pct <= 100)),
    muscle_pct numeric(6,2)
        check (muscle_pct is null or (muscle_pct > 0 and muscle_pct <= 100)),
    basal_calories numeric(10,2)
        check (basal_calories is null or basal_calories > 0),
    visceral_fat numeric(6,2)
        check (visceral_fat is null or visceral_fat > 0),
    metabolic_age integer
        check (metabolic_age is null or (metabolic_age > 0 and metabolic_age <= 150)),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_body_measurements_patient_date
    on public.body_measurements(patient_id, measured_on desc);

comment on column public.goals.calculation_method is
    'Método usado para la estimación; la meta final permanece editable por el profesional.';
comment on column public.goals.resting_calories is
    'Gasto energético en reposo usado como entrada, en kcal/día.';
comment on column public.body_measurements.basal_calories is
    'Valor informado por Tanita, Omron u otro equipo; no se calcula en la base de datos.';

alter table public.body_measurements enable row level security;

grant select, insert, update, delete on public.body_measurements to authenticated;
grant usage, select on sequence public.body_measurements_id_seq to authenticated;

drop policy if exists "body_measurements_select_allowed" on public.body_measurements;
create policy "body_measurements_select_allowed"
on public.body_measurements for select to authenticated
using ((select private.can_access_patient(patient_id)));

drop policy if exists "body_measurements_insert_allowed" on public.body_measurements;
create policy "body_measurements_insert_allowed"
on public.body_measurements for insert to authenticated
with check ((select private.can_access_patient(patient_id)));

drop policy if exists "body_measurements_update_allowed" on public.body_measurements;
create policy "body_measurements_update_allowed"
on public.body_measurements for update to authenticated
using ((select private.can_access_patient(patient_id)))
with check ((select private.can_access_patient(patient_id)));

drop policy if exists "body_measurements_delete_allowed" on public.body_measurements;
create policy "body_measurements_delete_allowed"
on public.body_measurements for delete to authenticated
using ((select private.can_access_patient(patient_id)));
