-- Mi Nutrición V0.7 - platillos frecuentes y recetas del nutriólogo.
-- Requiere haber ejecutado las migraciones V0.3 a V0.6.
-- Ejecutar una sola vez desde Supabase > SQL Editor con el rol postgres.

create table if not exists public.meal_templates (
    id uuid primary key default gen_random_uuid(),
    name text not null check (length(trim(name)) > 0),
    template_type text not null
        check (template_type in ('patient_favorite', 'nutritionist_recipe')),
    patient_id uuid references public.patients(id) on delete cascade,
    created_by uuid not null references public.profiles(id) on delete cascade,
    default_meal text not null default 'Comida'
        check (default_meal in ('Desayuno', 'Comida', 'Cena', 'Snack')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        (template_type = 'patient_favorite' and patient_id is not null)
        or (template_type = 'nutritionist_recipe' and patient_id is null)
    )
);

create table if not exists public.meal_template_items (
    id bigint generated by default as identity primary key,
    template_id uuid not null references public.meal_templates(id) on delete cascade,
    position integer not null default 1 check (position > 0),
    food_name text not null check (length(trim(food_name)) > 0),
    quantity numeric(10,2) not null check (quantity > 0),
    unit text not null check (length(trim(unit)) > 0),
    calories numeric(10,2) not null default 0 check (calories >= 0),
    protein numeric(10,2) not null default 0 check (protein >= 0),
    carbs numeric(10,2) not null default 0 check (carbs >= 0),
    fat numeric(10,2) not null default 0 check (fat >= 0),
    fiber numeric(10,2) not null default 0 check (fiber >= 0),
    water numeric(10,2) not null default 0 check (water >= 0),
    catalog_food_id uuid references public.food_catalog(id) on delete set null,
    source_name text,
    source_id text,
    created_at timestamptz not null default now()
);

create index if not exists idx_meal_templates_patient
    on public.meal_templates(patient_id);
create index if not exists idx_meal_templates_creator
    on public.meal_templates(created_by);
create index if not exists idx_meal_template_items_template
    on public.meal_template_items(template_id, position);

alter table public.meal_templates enable row level security;
alter table public.meal_template_items enable row level security;

create or replace function private.can_access_meal_template(target_template uuid)
returns boolean
language sql
stable
security definer set search_path = ''
as $$
    select exists (
        select 1
        from public.meal_templates mt
        where mt.id = target_template
          and (
              mt.created_by = (select auth.uid())
              or (
                  mt.template_type = 'patient_favorite'
                  and (select private.can_access_patient(mt.patient_id))
              )
              or (
                  mt.template_type = 'nutritionist_recipe'
                  and exists (
                      select 1
                      from public.nutritionist_patients np
                      where np.nutritionist_id = mt.created_by
                        and np.patient_id = (select private.current_patient_id())
                  )
              )
          )
    );
$$;

create or replace function public.create_meal_template(
    p_name text,
    p_template_type text,
    p_patient_id uuid,
    p_default_meal text,
    p_items jsonb
)
returns uuid
language plpgsql
security definer set search_path = ''
as $$
declare
    new_template_id uuid;
    item jsonb;
    item_position integer := 0;
begin
    if p_template_type not in ('patient_favorite', 'nutritionist_recipe') then
        raise exception 'Tipo de platillo inválido';
    end if;
    if nullif(trim(p_name), '') is null then
        raise exception 'El nombre del platillo es obligatorio';
    end if;
    if p_default_meal not in ('Desayuno', 'Comida', 'Cena', 'Snack') then
        raise exception 'Tiempo de comida inválido';
    end if;
    if jsonb_typeof(p_items) <> 'array'
       or jsonb_array_length(p_items) < 1
       or jsonb_array_length(p_items) > 30 then
        raise exception 'El platillo debe contener entre 1 y 30 componentes';
    end if;

    if p_template_type = 'patient_favorite' then
        if p_patient_id is null
           or p_patient_id <> (select private.current_patient_id()) then
            raise exception 'Sólo el paciente puede guardar sus platillos frecuentes';
        end if;
    else
        if not (select private.is_nutritionist()) or p_patient_id is not null then
            raise exception 'Sólo un nutriólogo puede crear recetas profesionales';
        end if;
    end if;

    insert into public.meal_templates (
        name, template_type, patient_id, created_by, default_meal
    ) values (
        trim(p_name), p_template_type, p_patient_id,
        (select auth.uid()), p_default_meal
    ) returning id into new_template_id;

    for item in select value from jsonb_array_elements(p_items) loop
        item_position := item_position + 1;
        if nullif(trim(coalesce(item ->> 'food_name', '')), '') is null then
            raise exception 'Cada componente requiere nombre';
        end if;
        if coalesce(nullif(item ->> 'quantity', '')::numeric, 0) <= 0 then
            raise exception 'Cada componente requiere una cantidad positiva';
        end if;

        insert into public.meal_template_items (
            template_id, position, food_name, quantity, unit,
            calories, protein, carbs, fat, fiber, water,
            catalog_food_id, source_name, source_id
        ) values (
            new_template_id,
            item_position,
            trim(item ->> 'food_name'),
            (item ->> 'quantity')::numeric,
            coalesce(nullif(trim(item ->> 'unit'), ''), 'porción'),
            greatest(coalesce(nullif(item ->> 'calories', '')::numeric, 0), 0),
            greatest(coalesce(nullif(item ->> 'protein', '')::numeric, 0), 0),
            greatest(coalesce(nullif(item ->> 'carbs', '')::numeric, 0), 0),
            greatest(coalesce(nullif(item ->> 'fat', '')::numeric, 0), 0),
            greatest(coalesce(nullif(item ->> 'fiber', '')::numeric, 0), 0),
            greatest(coalesce(nullif(item ->> 'water', '')::numeric, 0), 0),
            nullif(item ->> 'catalog_food_id', '')::uuid,
            nullif(trim(coalesce(item ->> 'source_name', '')), ''),
            nullif(trim(coalesce(item ->> 'source_id', '')), '')
        );
    end loop;

    return new_template_id;
end;
$$;

create or replace function public.delete_meal_template(p_template_id uuid)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
    delete from public.meal_templates
    where id = p_template_id
      and created_by = (select auth.uid());
    if not found then
        raise exception 'No se encontró un platillo propio con ese identificador';
    end if;
end;
$$;

grant select on public.meal_templates, public.meal_template_items to authenticated;
grant usage, select on sequence public.meal_template_items_id_seq to authenticated;

drop policy if exists "meal_templates_select_allowed" on public.meal_templates;
create policy "meal_templates_select_allowed"
on public.meal_templates for select to authenticated
using ((select private.can_access_meal_template(id)));

drop policy if exists "meal_template_items_select_allowed" on public.meal_template_items;
create policy "meal_template_items_select_allowed"
on public.meal_template_items for select to authenticated
using ((select private.can_access_meal_template(template_id)));

revoke all on function private.can_access_meal_template(uuid) from public;
grant execute on function private.can_access_meal_template(uuid) to authenticated;
revoke all on function public.create_meal_template(text, text, uuid, text, jsonb)
    from public, anon;
grant execute on function public.create_meal_template(text, text, uuid, text, jsonb)
    to authenticated;
revoke all on function public.delete_meal_template(uuid) from public, anon;
grant execute on function public.delete_meal_template(uuid) to authenticated;
